# __init__.py
from .pypdf2 import PyPdf2
from .pypdf4 import PyPdf4
from .pdfminer import PdfMiner
from .openpyxl import OpenPyXl
from .docx import Docx
from .csv import Csv
#from .pt_loader import load_pt
from .txt import Txt
from .json import Json
#from .xml import Xml
from .bs4 import load_html
from .md import Md
#from .rtf import Rtf
from .pptx import Pptx
#from .odp_loader import load_odp
#from .odt_loader import load_odt
#from .ods_loader import load_ods
#from .epub_loader import load_epub
#from .yaml_loader import load_yaml
from .sql import Sql
#from .db_loader import load_db
#from .tar_loader import load_tar
#from .zip_loader import load_zip
#from .rar_loader import load_rar
#from .image_loader import load_image
#from .jsonl_loader import load_jsonl
#from .ipynb_loader import load_ipynb
from .pickle import Pickle
#from .npy_loader import load_npy
from .scipy import Scipy
