from setuptools import setup, find_packages

setup(
  name = 'Indox',        
  version = '0.2',      
  license='MIT',      
  packages=find_packages(),
  package_data={'Indox': ['config.yaml']},
  include_package_data=True,  
  description = 'Indox Retrieval Augmentation',   
  author = 'nerdstudio',                  
  author_email = 'Mohammad@nematifamilyfundation.onmicrosoft.com',    
  url = 'https://github.com/osllmai/inDox',   
  keywords = ['RAG', 'LLM'],   
  install_requires=[           
          'langchain_community',
        'numpy',
        'openai',
        'pandas',
        'PyPDF2',
        'scikit_learn',
        'tenacity',
        'tiktoken',
        'umap_learn',
        'transformers',
        'black',
        'chromadb',
        'psycopg2',
        'pgvector',
        'langchain-openai',
        'langchain',
        'faiss-cpu',
      ],
  classifiers=[
    'Development Status :: 3 - Alpha',     
    'Intended Audience :: Developers',     
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',   
    'Programming Language :: Python :: 3',     
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
  ],
)
