from .csv import CSV
from .docx import Docx
from .excel import Excel
from .html import Html
from .json import Json
from .markdown import Markdown
from .pdfminer import PdfMiner
from .pdfplumber import PdfPlumber
from .pypdf2 import PyPdf2
from .pypdf4 import PyPdf4
from .sql import Sql
from .txt import Txt
