name: Tag and Release on Push

on:
  push:
    branches: [ "master", "development" ]
  workflow_dispatch:

jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    steps:

      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for tagging

      # Step 2: Gather deployment information
      - name: Gather Deployment Information
        id: gather_info
        run: |
          TIMESTAMP=$(date -u "+%A, %B %d %Y, %I:%M:%S %p UTC")
          TAG_NAME="v$(date +'%Y%m%d-%H%M%S')"
          VERSION_NAME="$(date +'%Y.%m.%d')"
          
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      # Step 3: Create and push a Git tag
      - name: Create and Push Git Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      # Step 4: Create a GitHub release
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $TAG_NAME \
            --title "Release $VERSION_NAME" \
            --notes "Automated release generated on $TIMESTAMP."
